version: '3'
services:

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwd # set your password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 5001:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwd # set your password

volumes:
  mysql_data:

# networks:
#   default:
#     external:
#       name: localhost